name: Build Paint Team 3D APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать проект
        uses: actions/checkout@v4

      - name: Установить Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Установить Android SDK
        uses: android-actions/setup-android@v3

      - name: Установить Gradle 8.7
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Собрать APK
        run: gradle assembleDebug

      - name: Загрузить APK
        uses: actions/upload-artifact@v4
        with:
          name: PaintTeam3D-debug-apk
          path: app/build/outputs/apk/debug/*.apk
