name: Build Paint Team 3D APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать проект
        uses: actions/checkout@v4

      - name: Собрать APK через Godot
        uses: dulvui/godot-android-export@v4
        with:
          godot-version: 4.6.1
          working-directory: .

      - name: Загрузить APK
        uses: actions/upload-artifact@v4
        with:
          name: PaintTeam3D-Android
          path: build/PaintTeam3D.apk
